export type Perks2Subcategory = {
  slug: string;
  title: string;
  description: string;
  slots: number;
  products?: Perks2Product[];
};

export type Perks2Product = {
  id: string;
  title: string;
  description: string;
  benefit: string;
  benefitLabel?: string;
  highlightValue: string;
  code: string | null;
  registerLink: string;
  registerLabel?: string;
  contactWeChat?: boolean;
  tutorialLink: string | null;
  recommendation: number;
  recommendationText: string;
  badge?: string;
  claimedCount?: number;
  iconUrl?: string;
  imageUrl?: string;
  imageAlt?: string;
};

export type Perks2Section = {
  slug: string;
  index: string;
  title: string;
  eyebrow: string;
  description: string;
  summary: string;
  subcategories: Perks2Subcategory[];
};

const onlineArticle = (path: string) => `https://www.wise-invest.org${path}`;

export const perkSections: Perks2Section[] = [
  {
    slug: "bank",
    index: "01",
    title: "银行卡",
    eyebrow: "Banking",
    description: "港卡、海外账户和见证开户资料集中放置。",
    summary: "适合需要跨境收付款、资金中转、港美股入金的用户。",
    subcategories: [
      {
        slug: "overseas-bank",
        title: "其他地区银行卡",
        description: "英国、新加坡、美国等地区账户。",
        slots: 3,
        products: [
          {
            id: "wise",
            title: "Wise",
            description: "全球汇款和货币兑换服务，适合跨境转账、多币种收付款和境外资金中转。",
            benefit: "汇款免手续费额度",
            benefitLabel: "福利额度",
            highlightValue: "$600",
            code: "ewke85g",
            registerLink: "https://wise.com/invite/ihpc/ewke85g",
            tutorialLink: "/articles/bank/Ysn8tPfj",
            recommendation: 4.8,
            recommendationText: "跨境常用",
            badge: "热门",
            claimedCount: 2100,
            iconUrl: "https://wise.com",
          },
          {
            id: "ifast",
            title: "iFast",
            description: "iFAST Global Bank 账户入口，适合补充海外账户、跨境收付款和资金管理。",
            benefit: "通过邀请链接注册开户",
            benefitLabel: "开户注册",
            highlightValue: "iFAST",
            code: "fengyangy4742",
            registerLink: "https://www.ifastgb.com/en/tellafriend/fengyangy4742",
            tutorialLink: "https://www.bilibili.com/video/BV1tz4qzvEN7",
            recommendation: 4.6,
            recommendationText: "视频教程",
            badge: "新补充",
            iconUrl: "https://www.ifastgb.com",
          },
          {
            id: "starryblu",
            title: "StarryBlu",
            description: "护照开同名 OCBC 账户，可用于跨境收款、消费、出金和入金盈透等场景。",
            benefit: "填写邀请码可获取额外奖励",
            benefitLabel: "开户奖励",
            highlightValue: "20SGD",
            code: "MPFK00F",
            registerLink: "/articles/vcard/uQfN0J0j",
            tutorialLink: "/articles/vcard/uQfN0J0j",
            recommendation: 4.7,
            recommendationText: "实测推荐",
            badge: "新实测",
            iconUrl: "/images/perks/starryblu-logo.png",
          },
        ],
      },
      {
        slug: "east-west-bank",
        title: "华美银行",
        description: "美国本土银行开户协助，适合搭配盈透证券构建美国银行 + 美券组合。",
        slots: 1,
      },
      {
        slug: "hong-kong-bank",
        title: "香港地区银行卡",
        description: "香港实体银行、港澳虚拟银行和数字银行。",
        slots: 10,
        products: [
          {
            id: "hsbc-hk",
            title: "汇丰银行",
            description: "人在香港即可线上开立 HSBC One，适合优先补齐实体港卡和日常跨境收付款。",
            benefit: "线上开立 HSBC One",
            benefitLabel: "开户路径",
            highlightValue: "HSBC",
            code: null,
            registerLink: onlineArticle("/articles/bank/WoxUXncV"),
            tutorialLink: onlineArticle("/articles/bank/WoxUXncV"),
            recommendation: 4.9,
            recommendationText: "实体首选",
            badge: "实体银行",
            iconUrl: "https://www.hsbc.com.hk",
          },
          {
            id: "bochk",
            title: "中银香港",
            description: "香港本地大型银行，适合准备实体港卡、港币账户和长期跨境资金管理。",
            benefit: "自在理财开户教程",
            benefitLabel: "开户路径",
            highlightValue: "BOCHK",
            code: null,
            registerLink: onlineArticle("/articles/bank/AO9Yfph5"),
            tutorialLink: onlineArticle("/articles/bank/AO9Yfph5"),
            recommendation: 4.7,
            recommendationText: "本地大行",
            badge: "实体银行",
            iconUrl: "https://www.bochk.com",
          },
          {
            id: "icbc-asia",
            title: "工银亚洲",
            description: "适合补充香港实体银行账户，教程覆盖开户材料、流程细节和后续使用注意事项。",
            benefit: "实体港卡开户教程",
            benefitLabel: "开户路径",
            highlightValue: "ICBC",
            code: null,
            registerLink: onlineArticle("/articles/bank/0uzSFs7d"),
            tutorialLink: onlineArticle("/articles/bank/0uzSFs7d"),
            recommendation: 4.5,
            recommendationText: "实体补充",
            badge: "实体银行",
            iconUrl: "https://www.icbcasia.com",
          },
          {
            id: "za-bank",
            title: "众安银行",
            description: "香港第一家虚拟银行，支持转数快、ZA Card、绑定国内消费和港美股投资。",
            benefit: "ZA Card 股票回赠与券包福利",
            benefitLabel: "邀请福利",
            highlightValue: "2.5%",
            code: "T659B7",
            registerLink: "https://l.za.group/Dsh3x",
            tutorialLink: onlineArticle("/articles/bank/4EB0zNOS"),
            recommendation: 5,
            recommendationText: "虚拟首选",
            badge: "专属邀请码",
            claimedCount: 760,
            iconUrl: "https://www.za.group",
          },
          {
            id: "ant-bank-hk",
            title: "蚂蚁银行香港",
            description: "蚂蚁集团旗下香港持牌虚拟银行，界面简洁，适合赴港期间快速补充虚拟港卡。",
            benefit: "四步完成开户申请",
            benefitLabel: "开户路径",
            highlightValue: "4步",
            code: null,
            registerLink: onlineArticle("/articles/bank/OwFAe2JD"),
            tutorialLink: onlineArticle("/articles/bank/OwFAe2JD"),
            recommendation: 4.5,
            recommendationText: "虚拟港卡",
            badge: "虚拟银行",
            iconUrl: "https://www.antbank.hk",
          },
          {
            id: "ant-bank-macau",
            title: "蚂蚁澳门",
            description: "澳门数字银行，可作为港澳账户组合补充，也支持港美股相关场景。",
            benefit: "入金门槛相对友好",
            benefitLabel: "产品亮点",
            highlightValue: "3k",
            code: null,
            registerLink: onlineArticle("/articles/bank/oYC1uLNW"),
            tutorialLink: onlineArticle("/articles/bank/oYC1uLNW"),
            recommendation: 4.4,
            recommendationText: "澳门补充",
            badge: "数字银行",
            iconUrl: "https://www.antbank.mo",
          },
          {
            id: "airstar-bank",
            title: "天星银行",
            description: "香港持牌虚拟银行，开户流程简洁，适合和众安、蚂蚁一起组成虚拟港卡组合。",
            benefit: "人在香港线上开户",
            benefitLabel: "开户路径",
            highlightValue: "Airstar",
            code: null,
            registerLink: onlineArticle("/articles/bank/ucHyMf8P"),
            tutorialLink: onlineArticle("/articles/bank/ucHyMf8P"),
            recommendation: 4.4,
            recommendationText: "虚拟港卡",
            badge: "虚拟银行",
            iconUrl: "https://www.airstarbank.com",
          },
          {
            id: "welab-bank",
            title: "汇立银行",
            description: "香港首批虚拟银行之一，支持 GoSave、FPS 转账和多货币借记卡使用场景。",
            benefit: "FPS 入金与借记卡教程",
            benefitLabel: "产品亮点",
            highlightValue: "WeLab",
            code: null,
            registerLink: onlineArticle("/articles/bank/wMpXaoI5"),
            tutorialLink: onlineArticle("/articles/bank/wMpXaoI5"),
            recommendation: 4.4,
            recommendationText: "虚拟港卡",
            badge: "虚拟银行",
            iconUrl: "https://www.welab.bank",
          },
          {
            id: "pao-bank",
            title: "平安数字",
            description: "香港持牌数字银行，储蓄账户资金可切换到港股、美股、基金等投资场景。",
            benefit: "新客活期 + 定期双 8%",
            benefitLabel: "新客福利",
            highlightValue: "8%",
            code: null,
            registerLink: onlineArticle("/articles/bank/wgBs7jp3"),
            tutorialLink: onlineArticle("/articles/bank/wgBs7jp3"),
            recommendation: 4.5,
            recommendationText: "数字银行",
            badge: "数字银行",
            iconUrl: "https://www.paob.com.hk",
          },
          {
            id: "sgb",
            title: "新加坡海湾",
            description: "Singapore Gulf Bank，适合关注跨境支付、无 CRS 组合和加密友好银行账户的用户。",
            benefit: "护照 + 身份证即可开户",
            benefitLabel: "产品亮点",
            highlightValue: "SGB",
            code: null,
            registerLink: onlineArticle("/articles/bank/cu2u5jRN"),
            tutorialLink: onlineArticle("/articles/bank/cu2u5jRN"),
            recommendation: 4.6,
            recommendationText: "跨境数字",
            badge: "数字银行",
            iconUrl: "https://www.sgb.com",
          },
        ],
      },
      {
        slug: "witness-account",
        title: "见证开户",
        description: "不用亲赴香港，在内地本地网点完成境外银行卡见证开户。",
        slots: 1,
      },
    ],
  },
  {
    slug: "crypto",
    index: "02",
    title: "加密",
    eyebrow: "Crypto",
    description: "交易所、链上工具、钱包和虚拟 U 卡入口。",
    summary: "适合需要手续费返佣、链上交易、资产保管和 U 卡消费的用户。",
    subcategories: [
      {
        slug: "uex-exchange",
        title: "CEX 交易所",
        description: "中心化交易所福利与注册入口。",
        slots: 4,
        products: [
          {
            id: "binance",
            title: "Binance 币安",
            description: "全球领先的加密货币交易所，适合新手完成注册、KYC、入金和基础交易。",
            benefit: "永久交易 & 钱包手续费减免",
            benefitLabel: "返佣比例",
            highlightValue: "20%",
            code: "WISE6666",
            registerLink: "https://www.bsmkweb.com/join?ref=WISE6666",
            tutorialLink: "/articles/crypto/GaM38JYk",
            recommendation: 5,
            recommendationText: "新手首开",
            badge: "编辑推荐",
            claimedCount: 3240,
            iconUrl: "https://www.binance.com",
          },
          {
            id: "okx",
            title: "OKX 欧易",
            description: "全球知名数字资产交易平台，界面清晰，适合完成入金、买币和日常现货交易。",
            benefit: "永久交易 & 钱包手续费减免",
            benefitLabel: "返佣比例",
            highlightValue: "20%",
            code: "WISE6666",
            registerLink: "https://www.vmutkhamuut.com/join/WISE6666",
            tutorialLink: "/articles/crypto/mAPQm7WZ",
            recommendation: 4.8,
            recommendationText: "入金常用",
            badge: "热门",
            claimedCount: 1890,
            iconUrl: "https://www.okx.com",
          },
          {
            id: "bitget",
            title: "Bitget",
            description: "加密货币衍生品交易平台，理财、跟单和活动较多，适合补充多交易所组合。",
            benefit: "手续费减免 & 新用户注册专享福利",
            benefitLabel: "返佣比例",
            highlightValue: "20%",
            code: "wise6666",
            registerLink: "https://partner.hdmune.cn/bg/m53rb8lg",
            tutorialLink: "/articles/crypto/k3RVVcw4",
            recommendation: 4.7,
            recommendationText: "跟单活动",
            badge: "活动多",
            claimedCount: 1120,
            iconUrl: "https://www.bitget.com",
          },
          {
            id: "bybit",
            title: "Bybit",
            description: "全球知名加密货币衍生品交易所，适合了解合约、理财和 LaunchPool 等玩法。",
            benefit: "手续费减免 & 注册即享交易优惠",
            benefitLabel: "返佣比例",
            highlightValue: "20%",
            code: "WISE6666",
            registerLink: "https://partner.bybit.com/b/WISE6666",
            tutorialLink: "/articles/crypto/e6utod7B",
            recommendation: 4.6,
            recommendationText: "衍生品强",
            badge: "补充选择",
            claimedCount: 980,
            iconUrl: "https://www.bybit.com",
          },
        ],
      },
      {
        slug: "onchain-wallet",
        title: "链上钱包",
        description: "Bitget、OKX、币安等 Web3 钱包入口。",
        slots: 3,
        products: [
          {
            id: "binance-wallet",
            title: "币安钱包",
            description: "币安 Web3 钱包，支持多链资产管理，适合从交易所过渡到链上使用。",
            benefit: "支持 DeFi、NFT 与跨链等链上场景",
            benefitLabel: "钱包能力",
            highlightValue: "多链",
            code: "WISE555",
            registerLink: "https://web3.binance.com/referral?ref=WISE555",
            tutorialLink: null,
            recommendation: 4.7,
            recommendationText: "编辑推荐",
            badge: "链上钱包",
            claimedCount: 560,
            iconUrl: "https://www.binance.com",
          },
          {
            id: "okx-wallet",
            title: "欧易钱包",
            description: "OKX Web3 钱包，一站式链上资产管理，适合 DeFi 交互、NFT 和跨链桥。",
            benefit: "多链钱包，支持 DeFi 交互与跨链桥",
            benefitLabel: "钱包能力",
            highlightValue: "多链",
            code: "WISE6666",
            registerLink: "https://web3.okx.com/join/WISE6666",
            tutorialLink: null,
            recommendation: 4.6,
            recommendationText: "链上常用",
            badge: "链上钱包",
            claimedCount: 380,
            iconUrl: "https://www.okx.com",
          },
          {
            id: "bitget-wallet",
            title: "Bitget 钱包",
            description: "Bitget Wallet，支持多链资产管理，也能衔接 Wallet Card 等支付场景。",
            benefit: "多链钱包 + Wallet Card 入口",
            benefitLabel: "钱包能力",
            highlightValue: "多链",
            code: "89zQdt",
            registerLink: "https://web3.bitget.com/invite/card/89zQdt?channel=Copylink&utm_source=newInviteRebate&inviteCode=89zQdt",
            tutorialLink: "/articles/vcard/WK8p1cCV",
            recommendation: 4.7,
            recommendationText: "钱包卡联动",
            badge: "链上钱包",
            claimedCount: 670,
            iconUrl: "https://www.bitget.com",
          },
        ],
      },
      {
        slug: "cold-wallet",
        title: "冷钱包",
        description: "硬件钱包、助记词和长期资产保管。",
        slots: 2,
        products: [
          {
            id: "safepal-cold-wallet",
            title: "SafePal X1 冷钱包",
            description: "SafePal 以硬件钱包起家，教程里包含通过邀请码领取 SafePal X1 冷钱包的路径。",
            benefit: "完成 SafePal 流程后可领取冷钱包",
            benefitLabel: "冷钱包",
            highlightValue: "X1",
            code: "884823",
            registerLink: "https://www.safepal.com/bank/register?referral=884823",
            tutorialLink: "/articles/vcard/E4lD5AIn",
            recommendation: 4.6,
            recommendationText: "资产保管",
            badge: "冷钱包",
            claimedCount: 430,
            iconUrl: "https://www.safepal.com",
          },
          {
            id: "onekey-cold-wallet",
            title: "OneKey",
            description: "OneKey 硬件钱包，适合长期离线保管多链资产，官网强调安全芯片和开源生态。",
            benefit: "通过专属链接购买 OneKey 硬件钱包",
            benefitLabel: "购买入口",
            highlightValue: "冷钱包",
            code: "Wise6666",
            registerLink: "https://onekey.so/r/Wise6666/shop",
            tutorialLink: "https://onekey.so/zh_CN/",
            recommendation: 4.7,
            recommendationText: "硬件保管",
            badge: "官方商城",
            iconUrl: "https://onekey.so",
            imageUrl: "/images/perks/onekey-pro.jpg",
            imageAlt: "OneKey Pro 硬件钱包官方产品图",
          },
        ],
      },
      {
        slug: "virtual-u-card",
        title: "虚拟 U 卡",
        description: "虚拟卡、订阅消费和出入金路径。",
        slots: 6,
        products: [
          {
            id: "bitget-virtual-card",
            title: "Bitget 虚拟 U 卡",
            description: "Bitget Wallet Card，可用于 Web3 到 Web2 的日常消费和支付场景。",
            benefit: "便捷的数字资产支付解决方案",
            benefitLabel: "产品定位",
            highlightValue: "数字支付",
            code: "89zQdt",
            registerLink: "https://web3.bitget.com/invite/card/89zQdt?channel=Copylink&utm_source=newInviteRebate&inviteCode=89zQdt",
            tutorialLink: "/articles/vcard/WK8p1cCV",
            recommendation: 4.8,
            recommendationText: "消费顺畅",
            badge: "新上线",
            claimedCount: 670,
            iconUrl: "https://www.bitget.com",
          },
          {
            id: "safepal-virtual-card",
            title: "SafePal 虚拟 U 卡",
            description: "SafePal 钱包虚拟 U 卡服务，适合加密资产支付、汇款和资金流转。",
            benefit: "安全便捷的加密货币支付卡",
            benefitLabel: "产品定位",
            highlightValue: "安全支付",
            code: "884823",
            registerLink: "https://www.safepal.com/bank/register?referral=884823",
            tutorialLink: "/articles/vcard/E4lD5AIn",
            recommendation: 4.6,
            recommendationText: "出入金友好",
            badge: "U 卡",
            claimedCount: 430,
            iconUrl: "https://www.safepal.com",
          },
          {
            id: "starryblu-virtual-card",
            title: "StarryBlu 虚拟 U 卡",
            description: "StarryBlu Visa 卡可用于线上线下消费、跨境支付和微信付款码等场景。",
            benefit: "填写邀请码可获取额外奖励，适合跨境消费和资金流转",
            benefitLabel: "消费入口",
            highlightValue: "Visa卡",
            code: "MPFK00F",
            registerLink: "/articles/vcard/uQfN0J0j",
            tutorialLink: "/articles/vcard/uQfN0J0j",
            recommendation: 4.7,
            recommendationText: "跨境消费",
            badge: "实测推荐",
            iconUrl: "/images/perks/starryblu-logo.png",
          },
          {
            id: "uuwallet-virtual-card",
            title: "UU Wallet 虚拟 U 卡",
            description: "Web3 支付平台，覆盖存、换、花、赚、转，适合虚拟卡消费和多场景支付。",
            benefit: "开虚拟卡 100% 返现，实体卡 50% 返现",
            benefitLabel: "返现福利",
            highlightValue: "100%返现",
            code: "d1wvsq",
            registerLink: "/articles/vcard/aQ7pEkbH",
            tutorialLink: "/articles/vcard/aQ7pEkbH",
            recommendation: 4.5,
            recommendationText: "低成本",
            badge: "新上线",
            iconUrl: "https://app.uuwallet.com",
          },
          {
            id: "benpay-virtual-card",
            title: "BenPay Delta Card",
            description: "无需 KYC 实名，无开卡费，适合订阅 ChatGPT、Claude 等 AI 会员。",
            benefit: "无需 KYC，即开即用，支持 AI 订阅",
            benefitLabel: "开卡门槛",
            highlightValue: "无 KYC",
            code: "9WJVG9",
            registerLink: "https://benpay.com/card?invite_code=9WJVG9",
            tutorialLink: "/articles/vcard/oCyhotvX",
            recommendation: 4.5,
            recommendationText: "AI 订阅",
            badge: "新上线",
            iconUrl: "https://benpay.com",
          },
          {
            id: "bybit-virtual-card",
            title: "Bybit 虚拟 U 卡",
            description: "Bybit 平台虚拟 U 卡，适合交易所账户用户开卡、充值和日常支付。",
            benefit: "开卡即享消费返现，支持 Google Pay / Apple Pay",
            benefitLabel: "消费返现",
            highlightValue: "10%返现",
            code: "JJKZWA4",
            registerLink: "https://www.bybit.com/en/card/",
            tutorialLink: "/articles/vcard/wYKRLDvK",
            recommendation: 4.4,
            recommendationText: "无护照补充",
            badge: "U 卡",
            claimedCount: 310,
            iconUrl: "https://www.bybit.com",
          },
        ],
      },
    ],
  },
  {
    slug: "broker",
    index: "03",
    title: "券商",
    eyebrow: "Broker",
    description: "美国券商、港资券商、链上美股和 A 股券商分开整理。",
    summary: "适合要开户、入金、交易港美股、A 股或尝试链上美股的用户。",
    subcategories: [
      {
        slug: "us-broker",
        title: "美资券商",
        description: "嘉信、第一、盈透等美国券商开户、入金和福利。",
        slots: 3,
        products: [
          {
            id: "charles-schwab",
            title: "嘉信理财",
            description: "全球知名综合券商，适合长期资产配置、美股交易和多品类资产管理。",
            benefit: "国际账户开户入口，支持美股及多品类资产配置",
            benefitLabel: "开户入口",
            highlightValue: "国际",
            code: null,
            registerLink: "https://international.schwab.com/open-account-intro/open-account?country=CH&branchCode=EO",
            tutorialLink: "/articles/broker/MWyWMwwN",
            recommendation: 4.7,
            recommendationText: "美资大行",
            badge: "美资券商",
            claimedCount: 290,
            iconUrl: "https://international.schwab.com",
          },
          {
            id: "diyi-securities",
            title: "第一证券",
            description: "美国本土券商，不参与 CRS，凭护照和地址证明即可开户，整体流程相对轻便。",
            benefit: "零佣金交易，注重隐私的内地投资者首选",
            benefitLabel: "交易佣金",
            highlightValue: "零佣金",
            code: null,
            registerLink: "https://www.firstrade.com/content/zh-tw/accounttypes",
            tutorialLink: "/articles/broker/eKIyMXl8",
            recommendation: 4.6,
            recommendationText: "轻便开户",
            badge: "美资券商",
            claimedCount: 120,
            iconUrl: "https://www.firstrade.com",
          },
          {
            id: "interactive-brokers",
            title: "盈透证券",
            description: "全球领先的在线券商，覆盖市场广，适合长期配置、专业交易和多币种账户管理。",
            benefit: "低佣金交易，全球市场覆盖",
            benefitLabel: "产品优势",
            highlightValue: "全球",
            code: null,
            registerLink: "https://ibkr.com/referral/fengyang247",
            tutorialLink: "/articles/broker/2Uh6hvvZ",
            recommendation: 4.9,
            recommendationText: "全球覆盖",
            badge: "编辑推荐",
            claimedCount: 890,
            iconUrl: "https://www.interactivebrokers.com",
          },
        ],
      },
      {
        slug: "hk-broker",
        title: "港资券商",
        description: "复星、致富、腾达、盈立、长桥等港美股券商入口。",
        slots: 5,
        products: [
          {
            id: "futu",
            title: "复星证券",
            description: "一站式港美股交易平台，教程覆盖开户、费率、福利和多种入金方式。",
            benefit: "开户即享交易优惠",
            benefitLabel: "开户福利",
            highlightValue: "开户礼",
            code: "AGVPK3",
            registerLink: "https://h5.fotechwealth.com/pages/startAccount.html?channel=030005&aeCode=B2&invitationCode=AGVPK3&langType=zhCn",
            tutorialLink: "/articles/broker/sQSbLRe8",
            recommendation: 4.8,
            recommendationText: "港资首选",
            badge: "编辑推荐",
            claimedCount: 520,
            iconUrl: "https://www.futuhk.com",
          },
          {
            id: "chief-securities",
            title: "致富证券",
            description: "香港本地老牌券商，支持港股、美股、打新和月供股票等投资场景。",
            benefit: "使用邀请码开户，享专属开户流程与活动支持",
            benefitLabel: "开户支持",
            highlightValue: "专属",
            code: "HN7787",
            registerLink: "https://service.chiefgroup.com.hk/account-open/login?PromoCode=HN7787",
            tutorialLink: "/articles/broker/GaobLP0X",
            recommendation: 4.6,
            recommendationText: "老牌港资",
            badge: "港资券商",
            claimedCount: 180,
            iconUrl: "https://www.chiefgroup.com.hk/",
          },
          {
            id: "tengda-securities",
            title: "腾达证券",
            description: "支持内地身份证开户，可用 StarryBlu、iFast、众安等路径入金港美股。",
            benefit: "入金等值 1 万港币，解锁港美股长期 0 佣金",
            benefitLabel: "交易佣金",
            highlightValue: "$0佣金",
            code: "XDG74RHG",
            registerLink: "https://gigamoney.app.wbrks.com/session/login?app_id=winner&org_id=1&account_channel=hk_winner&channel=kol&invite-code=XDG74RHG",
            tutorialLink: "/articles/broker/4k1kTctf",
            recommendation: 4.7,
            recommendationText: "国内开户",
            badge: "新实测",
            iconUrl: "https://gigamoney.app.wbrks.com",
          },
          {
            id: "usmart",
            title: "盈立证券",
            description: "智能港美股交易平台，适合通过低成本入金链路完成港美股投资。",
            benefit: "新用户注册专享福利",
            benefitLabel: "新人权益",
            highlightValue: "新人礼",
            code: "ckxq",
            registerLink: "https://www.usmart.com/",
            tutorialLink: null,
            recommendation: 4.4,
            recommendationText: "低成本链路",
            badge: "港资券商",
            claimedCount: 340,
            iconUrl: "https://hk.usmartglobal.com/zh-hk",
          },
          {
            id: "longbridge",
            title: "LongBridge 长桥",
            description: "新一代港美股券商，界面体验较好，适合补充港美股账户组合。",
            benefit: "入金送港美股终生免佣",
            benefitLabel: "开户福利",
            highlightValue: "终生免佣",
            code: "J8S4WK",
            registerLink: "https://app.lbmkt.ing/session/login?account_channel=lb&channel=HB100031&invite-code=J8S4WK",
            tutorialLink: null,
            recommendation: 4.4,
            recommendationText: "体验顺滑",
            badge: "港美股",
            claimedCount: 1450,
            iconUrl: "https://longbridgeapp.com",
          },
        ],
      },
      {
        slug: "onchain-stocks",
        title: "链上美股",
        description: "稳定币购买美股、链上券商和交易所资金入口。",
        slots: 4,
        products: [
          {
            id: "stablestock",
            title: "StableStock",
            description: "稳定币直购真实港美股的 TraDeFi 平台，支持 USDT/USDC 入金、港股打新和 900+ 标的交易。",
            benefit: "稳定币入金，港股打新，900+ 标的",
            benefitLabel: "链上美股",
            highlightValue: "20%",
            code: "WISE666",
            registerLink: "https://app.stablestock.finance/?join=WISE666",
            tutorialLink: "/articles/onchain/4OUbYina",
            recommendation: 4.8,
            recommendationText: "链上首选",
            badge: "新上线",
            iconUrl: "https://app.stablestock.finance",
          },
          {
            id: "binance-onchain-stocks",
            title: "币安美股入口",
            description: "适合先补齐币安账户和稳定币资金入口，后续衔接链上美股和代币化资产玩法。",
            benefit: "交易所账户 + 稳定币资金入口",
            benefitLabel: "资金入口",
            highlightValue: "BNB",
            code: "WISE6666",
            registerLink: "https://www.bsmkweb.com/join?ref=WISE6666",
            tutorialLink: "/articles/crypto/GaM38JYk",
            recommendation: 4.5,
            recommendationText: "交易所入口",
            badge: "待完善",
            claimedCount: 3240,
            iconUrl: "https://www.binance.com",
          },
          {
            id: "okx-onchain-stocks",
            title: "欧易美股入口",
            description: "适合使用欧易完成入金、买币和链上转账，为链上美股资金路径做准备。",
            benefit: "C2C 入金、稳定币和链上转账入口",
            benefitLabel: "资金入口",
            highlightValue: "OKX",
            code: "WISE6666",
            registerLink: "https://www.vmutkhamuut.com/join/WISE6666",
            tutorialLink: "/articles/crypto/mAPQm7WZ",
            recommendation: 4.5,
            recommendationText: "入金常用",
            badge: "待完善",
            claimedCount: 1890,
            iconUrl: "https://www.okx.com",
          },
          {
            id: "bitget-onchain-stocks",
            title: "Bitget 美股入口",
            description: "适合把 Bitget 作为补充交易所和稳定币通道，后续衔接链上美股资金流转。",
            benefit: "交易所账户、稳定币和链上转账入口",
            benefitLabel: "资金入口",
            highlightValue: "BGB",
            code: "wise6666",
            registerLink: "https://partner.hdmune.cn/bg/m53rb8lg",
            tutorialLink: "/articles/crypto/k3RVVcw4",
            recommendation: 4.4,
            recommendationText: "补充入口",
            badge: "待完善",
            claimedCount: 1120,
            iconUrl: "https://www.bitget.com",
          },
        ],
      },
      {
        slug: "a-share-broker",
        title: "A 股券商",
        description: "银河、华泰等 A 股账户开户和低佣费率协助。",
        slots: 2,
        products: [
          {
            id: "china-galaxy",
            title: "银河证券",
            description: "A 股大型券商，适合 ETF、股票、可转债、北交所和国债逆回购等场景。",
            benefit: "入金 1.5 万放 2 个月，ETF/LOF 可申请永久免五",
            benefitLabel: "核心权益",
            highlightValue: "永久免五",
            code: null,
            registerLink: "https://www.chinastock.com.cn/",
            registerLabel: "联系博主",
            contactWeChat: true,
            tutorialLink: null,
            recommendation: 4.7,
            recommendationText: "ETF 友好",
            badge: "编辑推荐",
            iconUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/9c/33/30/9c3330e7-b543-f9e6-65c3-bceeeac2d132/AppIcon-0-0-1x_U007emarketing-0-6-0-85-220.png/512x512bb.jpg",
          },
          {
            id: "huatai-securities",
            title: "华泰证券",
            description: "A 股头部券商，适合需要 SMART 量化交易、新客行情和较低佣金的用户。",
            benefit: "VIP 佣金万 1，新客赠 12 个月 10 档行情",
            benefitLabel: "佣金权益",
            highlightValue: "万1",
            code: null,
            registerLink: "https://www.htsc.com.cn/",
            registerLabel: "联系博主",
            contactWeChat: true,
            tutorialLink: null,
            recommendation: 4.6,
            recommendationText: "量化工具",
            badge: "A 股券商",
            iconUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/f0/4d/ce/f04dceaa-9b0b-771e-5af7-2060f57bec2d/AppIcon-0-0-1x_U007emarketing-0-8-0-0-85-220.png/512x512bb.jpg",
          },
        ],
      },
    ],
  },
  {
    slug: "ipo",
    index: "04",
    title: "打新",
    eyebrow: "IPO",
    description: "传统券商、链上券商和 A 股集合打新分开整理。",
    summary: "适合想看申购路径、平台选择、规则门槛和对应打新资料的用户。",
    subcategories: [
      {
        slug: "traditional-broker-ipo",
        title: "传统券商打新",
        description: "通过复星、致富等传统港资券商参与港股新股申购、融资打新和暗盘交易。",
        slots: 2,
        products: [
          {
            id: "futu-ipo",
            title: "复星证券打新",
            description: "复星证券支持港股新股申购及暗盘交易，适合已经配置港卡或可完成港资券商开户的用户。",
            benefit: "现金打新免费，融资打新手续费较低",
            benefitLabel: "打新费用",
            highlightValue: "现金免费",
            code: "AGVPK3",
            registerLink: "https://h5.fotechwealth.com/pages/startAccount.html?channel=030005&aeCode=B2&invitationCode=AGVPK3&langType=zhCn",
            registerLabel: "去开户",
            tutorialLink: "/articles/broker/sQSbLRe8",
            recommendation: 4.8,
            recommendationText: "传统首选",
            badge: "编辑推荐",
            claimedCount: 520,
            iconUrl: "https://www.futuhk.com",
          },
          {
            id: "chief-securities-ipo",
            title: "致富证券打新",
            description: "致富证券是香港本地老牌券商，支持港股、美股、IPO 打新和月供股票等投资场景。",
            benefit: "内地身份证可线上开户，适合补充传统券商打新账户",
            benefitLabel: "开户路径",
            highlightValue: "线上开户",
            code: "HN7787",
            registerLink: "https://service.chiefgroup.com.hk/account-open/login?PromoCode=HN7787",
            registerLabel: "去开户",
            tutorialLink: "/articles/broker/GaobLP0X",
            recommendation: 4.6,
            recommendationText: "老牌港资",
            badge: "传统券商",
            claimedCount: 180,
            iconUrl: "https://www.chiefgroup.com.hk/",
          },
        ],
      },
      {
        slug: "onchain-broker-ipo",
        title: "链上券商打新",
        description: "通过稳定币和链上券商路径参与港股打新，后续新产品会继续补充。",
        slots: 2,
        products: [
          {
            id: "stablestock-ipo",
            title: "StableStock 打新",
            description: "StableStock 支持 USDT/USDC 入金和港股 IPO 打新，适合资金本来就在 Web3 里的用户。",
            benefit: "无需港卡或传统券商，可用稳定币参与港股打新",
            benefitLabel: "链上打新",
            highlightValue: "U进U出",
            code: "WISE666",
            registerLink: "https://app.stablestock.finance/?join=WISE666",
            registerLabel: "去打新",
            tutorialLink: "/articles/onchain/4OUbYina",
            recommendation: 4.8,
            recommendationText: "链上首选",
            badge: "新上线",
            iconUrl: "https://app.stablestock.finance",
          },
          {
            id: "stockcoin-ipo",
            title: "StockCoin",
            description: "Stockcoin.ai 是加密原生的股票与衍生品交易入口，适合补充链上券商和稳定币交易路径。",
            benefit: "通过邀请链接注册账户，后续可衔接链上券商打新和美股交易场景",
            benefitLabel: "链上券商",
            highlightValue: "StockCoin",
            code: "QSNRLQ",
            registerLink: "https://stockcoin.ai/zh-tw/register?ref=QSNRLQ",
            registerLabel: "去注册",
            tutorialLink: null,
            recommendation: 4.6,
            recommendationText: "新补充",
            badge: "新产品",
            iconUrl: "/images/perks/stockcoin-icon.svg",
          },
        ],
      },
      {
        slug: "a-share-ipo",
        title: "A 股打新",
        description: "A 股账户打新和 WiseInvest 集合打新业务入口。",
        slots: 2,
        products: [
          {
            id: "china-galaxy-ipo",
            title: "银河证券 A 股打新",
            description: "通过银河证券补齐 A 股账户，适合参与新股申购、ETF 交易和低佣场景。",
            benefit: "入金 1.5 万放 2 个月，ETF/LOF 可申请永久免五",
            benefitLabel: "开户权益",
            highlightValue: "A股账户",
            code: null,
            registerLink: "https://www.chinastock.com.cn/",
            registerLabel: "联系博主",
            contactWeChat: true,
            tutorialLink: null,
            recommendation: 4.7,
            recommendationText: "A 股入口",
            badge: "编辑推荐",
            iconUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/9c/33/30/9c3330e7-b543-f9e6-65c3-bceeeac2d132/AppIcon-0-0-1x_U007emarketing-0-6-0-85-220.png/512x512bb.jpg",
          },
          {
            id: "wiseinvest-collective-ipo",
            title: "WiseInvest 集合打新",
            description: "利用现有 A 股持仓参与集合申购，在股票涨跌之外获取稳定的阿尔法超额收益。",
            benefit: "已有持仓即可了解集合申购流程，页面内有收益、风险和参与方式说明",
            benefitLabel: "业务入口",
            highlightValue: "3%～10%",
            code: null,
            registerLink: "/ipo",
            registerLabel: "查看界面",
            tutorialLink: null,
            recommendation: 4.8,
            recommendationText: "集合打新",
            badge: "专属业务",
            iconUrl: "https://www.wise-invest.org",
          },
        ],
      },
    ],
  },
  {
    slug: "global-access",
    index: "05",
    title: "国际互联",
    eyebrow: "Global Access",
    description: "海外手机卡、eSIM 读卡器和跨境联网工具放在一起。",
    summary: "适合跨境出行、海外应用注册、境外账号维护的用户。",
    subcategories: [
      {
        slug: "esim",
        title: "eSIM 手机卡",
        description: "海外手机号、境外应用注册和长期保号入口。",
        slots: 1,
        products: [
          {
            id: "giffgaff-sim",
            title: "giffgaff 英国手机卡",
            description: "英国真实手机号，适合注册 PayPal、WhatsApp、海外 App Store 和接收平台验证码。",
            benefit: "国内购买后快递到家，按教程完成激活和保号",
            benefitLabel: "手机卡",
            highlightValue: "免月租",
            code: null,
            registerLink: "https://www.wise-sim.org/shop/giffgaff",
            registerLabel: "去购买",
            tutorialLink: "https://www.wise-sim.org/guides",
            recommendation: 4.8,
            recommendationText: "保号常用",
            badge: "Wise SIM",
            iconUrl: "https://www.wise-sim.org",
          },
        ],
      },
      {
        slug: "esim-reader",
        title: "eSIM 读卡器",
        description: "写卡设备、多卡管理和实体 eUICC 方案。",
        slots: 2,
        products: [
          {
            id: "xesim-card",
            title: "XeSIM X2 Pro",
            description: "实体 eUICC 卡，可在不支持原生 eSIM 的设备上写入和管理多个 eSIM 配置。",
            benefit: "通过返佣链接购买，输入折扣码可享 10% 减免",
            benefitLabel: "购买减免",
            highlightValue: "10%",
            code: "WISE666",
            registerLink: "https://xesim.cc/?DIST=RkJHFVg%3D",
            registerLabel: "去购买",
            tutorialLink: onlineArticle("/articles/simcard/EAN52fdr"),
            recommendation: 4.6,
            recommendationText: "九折减免",
            badge: "返佣链接",
            iconUrl: "https://xesim.cc",
          },
          {
            id: "beesim-reader",
            title: "BeeSIM 蓝牙 eSIM 工具卡",
            description: "蓝牙 eSIM 工具卡，适合国行手机、老款安卓和鸿蒙设备写入并管理 eSIM。",
            benefit: "教程内包含淘宝检索码和 20 元优惠券说明",
            benefitLabel: "购买方式",
            highlightValue: "20元券",
            code: null,
            registerLink: onlineArticle("/articles/simcard/OgtIzhMm"),
            registerLabel: "看购买方式",
            tutorialLink: onlineArticle("/articles/simcard/OgtIzhMm"),
            recommendation: 4.5,
            recommendationText: "蓝牙写卡",
            badge: "读卡器",
          },
        ],
      },
    ],
  },
  {
    slug: "other-resources",
    index: "06",
    title: "其他资源",
    eyebrow: "Other Resources",
    description: "订阅服务、AI 中转和海外账号资源。",
    summary: "适合需要低成本订阅、模型 API 中转和海外账号注册方案的用户。",
    subcategories: [
      {
        slug: "subscription-service",
        title: "订阅服务",
        description: "海外工具、流媒体和软件会员订阅资源。",
        slots: 1,
        products: [
          {
            id: "gamsgo",
            title: "GamsGo 会员合租",
            description: "连续多年提供数字订阅服务，覆盖 ChatGPT、Gemini、Grok、Notion、Gamma、Canva 等工具。",
            benefit: "低成本共享主流订阅，支持支付宝付款",
            benefitLabel: "订阅方式",
            highlightValue: "低成本",
            code: null,
            registerLink: "https://www.gamsgo.com/partner/GwZjT",
            tutorialLink: "/articles/ai/AYoe5wH7",
            recommendation: 4.6,
            recommendationText: "订阅常用",
            badge: "订阅服务",
            claimedCount: 890,
            iconUrl: "https://www.gamsgo.com/",
          },
        ],
      },
      {
        slug: "ai-relay",
        title: "AI 中转",
        description: "模型 API、额度管理和低成本调用入口。",
        slots: 1,
        products: [
          {
            id: "xueding-ai",
            title: "薛定 AI 中转站",
            description: "提供 ChatGPT、Claude、Gemini 等主流大模型 API 中转服务，稳定高速，按量计费。",
            benefit: "顶级 AI 模型低价直连",
            benefitLabel: "API 中转",
            highlightValue: "低价",
            code: "X227LE6M",
            registerLink: "https://shop.xuedingtoken.com/?invite=X227LE6M",
            tutorialLink: null,
            recommendation: 4.5,
            recommendationText: "模型中转",
            badge: "AI 中转",
            iconUrl: "https://xuedingtoken.com",
          },
        ],
      },
      {
        slug: "account-service",
        title: "账号服务",
        description: "海外账号注册、激活和出海必备账号方案。",
        slots: 1,
        products: [
          {
            id: "account-planet",
            title: "账号星球",
            description: "专注解决出海必备账号注册难题，覆盖主流平台账号注册与激活流程。",
            benefit: "海外账号注册一站式方案",
            benefitLabel: "账号服务",
            highlightValue: "账号",
            code: null,
            registerLink: "https://wiseinvest.acceboy.com/",
            tutorialLink: null,
            recommendation: 4.4,
            recommendationText: "账号资源",
            badge: "出海账号",
            claimedCount: 320,
            iconUrl: "https://wiseinvest.acceboy.com/",
          },
        ],
      },
    ],
  },
];

export const totalSubcategoryCount = perkSections.reduce(
  (sum, section) => sum + section.subcategories.length,
  0
);

export const totalProductSlotCount = perkSections.reduce(
  (sum, section) =>
    sum + section.subcategories.reduce((inner, subcategory) => inner + subcategory.slots, 0),
  0
);

export function getPerks2Section(slug: string) {
  return perkSections.find((section) => section.slug === slug);
}
