// ========== Perks Data ==========

export interface Perk {
  id: string;
  platform: string;
  category: "Crypto" | "Banking" | "Stocks" | "VirtualCard" | "Wallet";
  description: string;
  benefit: string;
  highlightValue: string; // 大字展示的核心价值，如 "20%"、"终生免佣"
  badge?: "编辑推荐" | "热门" | "新上线" | "限时";
  featured?: boolean; // 每个 section 的精选大卡
  claimedCount?: number; // 已领取人数（社会证明）
  code: string | null;
  link: string;
  iconUrl?: string;
  tutorialLink: string | null;
  tutorialImage?: string | null;
  color: string;
}

export const perks: Perk[] = [
  // 加密货币
  {
    id: "binance",
    platform: "Binance",
    category: "Crypto",
    description: "全球领先的加密货币交易所",
    benefit: "永久交易 & 钱包手续费减免",
    highlightValue: "20%",
    badge: "编辑推荐",
    featured: true,
    claimedCount: 3240,
    code: "WISE6666",
    link: "https://www.bsmkweb.com/join?ref=WISE6666",
    iconUrl: "https://www.binance.com",
    tutorialLink: "https://x.com/WiseInvest513/status/1970757919500120451",
    color: "#F3BA2F",
  },
  {
    id: "okx",
    platform: "OKX",
    category: "Crypto",
    description: "全球知名数字资产交易平台",
    benefit: "永久交易 & 钱包手续费减免",
    highlightValue: "20%",
    claimedCount: 1890,
    code: "WISE6666",
    link: "https://www.vmutkhamuut.com/join/WISE6666",
    iconUrl: "https://www.okx.com",
    tutorialLink: "https://x.com/WiseInvest513/status/1953466482576556465",
    color: "#000000",
  },
  {
    id: "bitget",
    platform: "Bitget",
    category: "Crypto",
    description: "全球领先的加密货币衍生品交易平台",
    benefit: "手续费减免 & 新用户注册专享福利",
    highlightValue: "20%",
    claimedCount: 1120,
    code: "wise6666",
    link: "https://partner.hdmune.cn/bg/m53rb8lg",
    iconUrl: "https://www.bitget.com",
    tutorialLink: "https://x.com/WiseInvest513/status/1980140049267343697",
    color: "#03C87C",
  },
  {
    id: "bybit",
    platform: "Bybit",
    category: "Crypto",
    description: "全球知名加密货币衍生品交易所",
    benefit: "手续费减免 & 注册即享交易优惠",
    highlightValue: "20%",
    claimedCount: 980,
    code: "WISE6666",
    link: "https://partner.bybit.com/b/WISE6666",
    iconUrl: "https://www.bybit.com",
    tutorialLink: "https://x.com/WiseInvest513/status/1980641416243212480",
    color: "#F8A33C",
  },
  // 银行服务
  {
    id: "wise",
    platform: "Wise",
    category: "Banking",
    description: "全球汇款和货币兑换服务",
    benefit: "汇款免手续费额度",
    highlightValue: "$600",
    badge: "热门",
    featured: true,
    claimedCount: 2100,
    code: "ewke85g",
    link: "https://wise.com/invite/ihpc/ewke85g",
    iconUrl: "https://wise.com",
    tutorialLink: "https://x.com/WiseInvest513/status/1996859457494737003",
    color: "#00B9FF",
  },
  {
    id: "zhongan-bank",
    platform: "众安银行",
    category: "Banking",
    description: "香港虚拟银行",
    benefit: "开户即享专属优惠",
    highlightValue: "专属礼",
    claimedCount: 760,
    code: "T659B7",
    link: "https://l.za.group/Dsh3x",
    iconUrl: "https://www.za.group",
    tutorialLink: "https://x.com/WiseInvest513/status/1979423189169246371",
    color: "#00A0E9",
  },
  // 股票交易
  {
    id: "longbridge",
    platform: "LongBridge 长桥",
    category: "Stocks",
    description: "新一代港美股券商",
    benefit: "入金送港美股终生免佣",
    highlightValue: "终生免佣",
    claimedCount: 1450,
    code: "J8S4WK",
    link: "https://app.lbmkt.ing/session/login?account_channel=lb&channel=HB100031&invite-code=J8S4WK",
    iconUrl: "https://longbridgeapp.com",
    tutorialLink: "https://x.com/WiseInvest513",
    color: "#1E88E5",
  },
  {
    id: "interactive-brokers",
    platform: "盈透证券",
    category: "Stocks",
    description: "全球领先的在线券商",
    benefit: "低佣金交易，全球市场覆盖",
    highlightValue: "全球",
    claimedCount: 890,
    code: null,
    link: "https://ibkr.com/referral/fengyang247",
    iconUrl: "https://www.interactivebrokers.com",
    tutorialLink: "https://x.com/WiseInvest513",
    color: "#003366",
  },
  {
    id: "usmart",
    platform: "盈立证券",
    category: "Stocks",
    description: "智能港美股交易平台",
    benefit: "新用户注册专享福利",
    highlightValue: "新人礼",
    claimedCount: 340,
    code: "ckxq",
    link: "https://www.usmart.com/",
    iconUrl: "https://hk.usmartglobal.com/zh-hk",
    tutorialLink: "https://x.com/WiseInvest513/status/1970789148605948258",
    color: "#FF6B35",
  },
  {
    id: "futu",
    platform: "复星证券",
    category: "Stocks",
    description: "一站式港美股交易平台",
    benefit: "开户即享交易优惠",
    highlightValue: "开户礼",
    badge: "编辑推荐",
    featured: true,
    claimedCount: 520,
    code: "AGVPK3",
    link: "https://h5.fotechwealth.com/pages/startAccount.html?channel=030005&aeCode=B2&invitationCode=AGVPK3&langType=zhCn",
    iconUrl: "https://www.futuhk.com",
    tutorialLink: "https://x.com/WiseInvest513/status/2037797205491515684",
    color: "#1A1A1A",
  },
  {
    id: "chief-securities",
    platform: "致富证券",
    category: "Stocks",
    description: "香港本地老牌券商，支持港美股账户开设",
    benefit: "使用邀请码开户，享专属开户流程与活动支持",
    highlightValue: "专属",
    claimedCount: 180,
    code: "HN7787",
    link: "https://service.chiefgroup.com.hk/account-open/login?PromoCode=HN7787",
    iconUrl: "https://www.chiefgroup.com.hk/",
    tutorialLink: "https://x.com/WiseInvest513/status/2018884799763775532",
    color: "#2563EB",
  },
  {
    id: "charles-schwab",
    platform: "嘉信理财",
    category: "Stocks",
    description: "全球知名综合券商，适合长期资产配置与跨市场投资",
    benefit: "国际账户开户入口，支持美股及多品类资产配置",
    highlightValue: "国际",
    claimedCount: 290,
    code: null,
    link: "https://international.schwab.com/open-account-intro/open-account?country=CH&branchCode=EO",
    iconUrl: "https://international.schwab.com",
    tutorialLink: "https://x.com/WiseInvest513/status/2019609350898413685",
    color: "#0073CF",
  },
  // 虚拟 U 卡
  {
    id: "bitget-virtual-card",
    platform: "Bitget 虚拟 U 卡",
    category: "VirtualCard",
    description: "Bitget 平台虚拟 U 卡服务",
    benefit: "便捷的数字资产支付解决方案",
    highlightValue: "数字支付",
    badge: "新上线",
    featured: true,
    claimedCount: 670,
    code: "89zQdt",
    link: "https://web3.bitget.com/invite/card/89zQdt?channel=Copylink&utm_source=newInviteRebate&inviteCode=89zQdt",
    iconUrl: "https://www.bitget.com",
    tutorialLink: "https://youtu.be/ZxElS0gVpY4",
    color: "#03C87C",
  },
  {
    id: "safepal-virtual-card",
    platform: "SafePal 虚拟 U 卡",
    category: "VirtualCard",
    description: "SafePal 钱包虚拟 U 卡服务",
    benefit: "安全便捷的加密货币支付卡",
    highlightValue: "安全支付",
    claimedCount: 430,
    code: "884823",
    link: "https://www.safepal.com/bank/register?referral=884823",
    iconUrl: "https://www.safepal.com",
    tutorialLink: "https://youtu.be/1Lw8VssYFNE",
    color: "#4F46E5",
  },
  // 链上钱包
  {
    id: "binance-wallet",
    platform: "币安钱包",
    category: "Wallet",
    description: "币安 Web3 钱包，支持多链资产管理",
    benefit: "安全易用的多链钱包，支持 DeFi、NFT 与跨链",
    highlightValue: "多链",
    badge: "编辑推荐",
    featured: true,
    claimedCount: 560,
    code: "WISE555",
    link: "https://web3.binance.com/referral?ref=WISE555",
    iconUrl: "https://www.binance.com",
    tutorialLink: null,
    tutorialImage: "/images/perks/币安钱包返现.png",
    color: "#F3BA2F",
  },
  {
    id: "okx-wallet",
    platform: "欧易钱包",
    category: "Wallet",
    description: "OKX Web3 钱包，一站式链上资产管理",
    benefit: "多链钱包，支持 DeFi 交互、NFT 与跨链桥",
    highlightValue: "多链",
    claimedCount: 380,
    code: "WISE6666",
    link: "https://web3.okx.com/join/WISE6666",
    iconUrl: "https://www.okx.com",
    tutorialLink: null,
    tutorialImage: "/images/perks/欧易钱包返现.png",
    color: "#000000",
  },
];
