// ========== Perks Data ==========

export interface Perk {
  id: string;
  platform: string;
  category: "Crypto" | "Banking" | "Stocks" | "VirtualCard" | "Wallet" | "AStocks";
  description: string;
  benefit: string;
  highlightValue: string; // 大字展示的核心价值，如 "20%"、"终生免佣"
  badge?: "编辑推荐" | "热门" | "新上线" | "限时";
  featured?: boolean; // 每个 section 的精选大卡
  claimedCount?: number; // 已领取人数（社会证明）
  code: string | null;
  link: string;
  iconUrl?: string;
  tutorialLink: string | null;
  tutorialImage?: string | null;
  color: string;
  details?: string[]; // 费率/条款详细说明
  contactWeChat?: boolean; // 点击领取时弹出微信联系二维码
  notice?: string; // 红字特别提示
}

export const perks: Perk[] = [
  // 加密货币
  {
    id: "binance",
    platform: "Binance",
    category: "Crypto",
    description: "全球领先的加密货币交易所",
    benefit: "永久交易 & 钱包手续费减免",
    highlightValue: "20%",
    badge: "编辑推荐",
    featured: true,
    claimedCount: 3240,
    code: "WISE6666",
    link: "https://www.bsmkweb.com/join?ref=WISE6666",
    iconUrl: "https://www.binance.com",
    tutorialLink: "/articles/crypto/GaM38JYk",
    color: "#F3BA2F",
  },
  {
    id: "okx",
    platform: "OKX",
    category: "Crypto",
    description: "全球知名数字资产交易平台",
    benefit: "永久交易 & 钱包手续费减免",
    highlightValue: "20%",
    claimedCount: 1890,
    code: "WISE6666",
    link: "https://www.vmutkhamuut.com/join/WISE6666",
    iconUrl: "https://www.okx.com",
    tutorialLink: "/articles/crypto/mAPQm7WZ",
    color: "#000000",
  },
  {
    id: "bitget",
    platform: "Bitget",
    category: "Crypto",
    description: "全球领先的加密货币衍生品交易平台",
    benefit: "手续费减免 & 新用户注册专享福利",
    highlightValue: "20%",
    claimedCount: 1120,
    code: "wise6666",
    link: "https://partner.hdmune.cn/bg/m53rb8lg",
    iconUrl: "https://www.bitget.com",
    tutorialLink: "/articles/crypto/k3RVVcw4",
    color: "#03C87C",
  },
  {
    id: "bybit",
    platform: "Bybit",
    category: "Crypto",
    description: "全球知名加密货币衍生品交易所",
    benefit: "手续费减免 & 注册即享交易优惠",
    highlightValue: "20%",
    claimedCount: 980,
    code: "WISE6666",
    link: "https://partner.bybit.com/b/WISE6666",
    iconUrl: "https://www.bybit.com",
    tutorialLink: "/articles/crypto/e6utod7B",
    color: "#F8A33C",
  },
  // 银行服务
  {
    id: "wise",
    platform: "Wise",
    category: "Banking",
    description: "全球汇款和货币兑换服务",
    benefit: "汇款免手续费额度",
    highlightValue: "$600",
    badge: "热门",
    featured: true,
    claimedCount: 2100,
    code: "ewke85g",
    link: "https://wise.com/invite/ihpc/ewke85g",
    iconUrl: "https://wise.com",
    tutorialLink: "/articles/bank/Ysn8tPfj",
    color: "#00B9FF",
  },
  {
    id: "zhongan-bank",
    platform: "众安银行",
    category: "Banking",
    description: "香港虚拟银行",
    benefit: "开户即享专属优惠",
    highlightValue: "专属礼",
    claimedCount: 760,
    code: "T659B7",
    link: "https://l.za.group/Dsh3x",
    iconUrl: "https://www.za.group",
    tutorialLink: "/articles/bank/2aiiqnjt",
    color: "#00A0E9",
  },
  {
    id: "east-west-bank",
    platform: "华美银行",
    category: "Banking",
    description: "美国本土银行，总部位于加州，专注服务华人社区",
    benefit: "配合盈透证券，实现美国银行 + 美券无 CRS 组合",
    highlightValue: "无 CRS",
    claimedCount: 0,
    code: null,
    link: "#",
    iconUrl: "https://www.eastwestbank.com",
    tutorialLink: null,
    color: "#B91C1C",
    contactWeChat: true,
    notice: "联系博主协助开户，备注「华美银行」即可",
    details: [
      "##核心优势",
      "美国本土银行，不参与 CRS，账户信息不上报中国税务局",
      "配合盈透证券（IBKR）打造完整美国金融体系",
      "支持 ACH / 电汇，与 IBKR 资金划转顺畅",
      "##适合人群",
      "希望资产合规出海、规避 CRS 申报的投资者",
      "已持有或计划开设盈透证券账户的用户",
      "##开户方式",
      "需联系博主协助，备注「华美银行」添加好友",
    ],
  },
  // 股票交易
  {
    id: "longbridge",
    platform: "LongBridge 长桥",
    category: "Stocks",
    description: "新一代港美股券商",
    benefit: "入金送港美股终生免佣",
    highlightValue: "终生免佣",
    claimedCount: 1450,
    code: "J8S4WK",
    link: "https://app.lbmkt.ing/session/login?account_channel=lb&channel=HB100031&invite-code=J8S4WK",
    iconUrl: "https://longbridgeapp.com",
    tutorialLink: "https://x.com/WiseInvest513",
    color: "#1E88E5",
  },
  {
    id: "interactive-brokers",
    platform: "盈透证券",
    category: "Stocks",
    description: "全球领先的在线券商",
    benefit: "低佣金交易，全球市场覆盖",
    highlightValue: "全球",
    claimedCount: 890,
    code: null,
    link: "https://ibkr.com/referral/fengyang247",
    iconUrl: "https://www.interactivebrokers.com",
    tutorialLink: "https://x.com/WiseInvest513",
    color: "#003366",
    contactWeChat: true,
    notice: "现已放开注册，可联系博主协助开户",
  },
  {
    id: "usmart",
    platform: "盈立证券",
    category: "Stocks",
    description: "智能港美股交易平台",
    benefit: "新用户注册专享福利",
    highlightValue: "新人礼",
    claimedCount: 340,
    code: "ckxq",
    link: "https://www.usmart.com/",
    iconUrl: "https://hk.usmartglobal.com/zh-hk",
    tutorialLink: "https://x.com/WiseInvest513/status/1970789148605948258",
    color: "#FF6B35",
  },
  {
    id: "futu",
    platform: "复星证券",
    category: "Stocks",
    description: "一站式港美股交易平台",
    benefit: "开户即享交易优惠",
    highlightValue: "开户礼",
    badge: "编辑推荐",
    featured: true,
    claimedCount: 520,
    code: "AGVPK3",
    link: "https://h5.fotechwealth.com/pages/startAccount.html?channel=030005&aeCode=B2&invitationCode=AGVPK3&langType=zhCn",
    iconUrl: "https://www.futuhk.com",
    tutorialLink: "/articles/broker/sQSbLRe8",
    color: "#1A1A1A",
  },
  {
    id: "chief-securities",
    platform: "致富证券",
    category: "Stocks",
    description: "香港本地老牌券商，支持港美股账户开设",
    benefit: "使用邀请码开户，享专属开户流程与活动支持",
    highlightValue: "专属",
    claimedCount: 180,
    code: "HN7787",
    link: "https://service.chiefgroup.com.hk/account-open/login?PromoCode=HN7787",
    iconUrl: "https://www.chiefgroup.com.hk/",
    tutorialLink: "/articles/broker/GaobLP0X",
    color: "#2563EB",
  },
  {
    id: "charles-schwab",
    platform: "嘉信理财",
    category: "Stocks",
    description: "全球知名综合券商，适合长期资产配置与跨市场投资",
    benefit: "国际账户开户入口，支持美股及多品类资产配置",
    highlightValue: "国际",
    claimedCount: 290,
    code: null,
    link: "https://international.schwab.com/open-account-intro/open-account?country=CH&branchCode=EO",
    iconUrl: "https://international.schwab.com",
    tutorialLink: "/articles/broker/MWyWMwwN",
    color: "#0073CF",
  },
  {
    id: "diyi-securities",
    platform: "第一证券",
    category: "Stocks",
    description: "美国本土券商，不参与 CRS，凭护照即可开户",
    benefit: "零佣金交易，注重隐私的内地投资者首选",
    highlightValue: "零佣金",
    claimedCount: 120,
    code: null,
    link: "https://www.firstrade.com/content/zh-tw/accounttypes",
    iconUrl: "https://www.firstrade.com",
    tutorialLink: "/articles/broker/eKIyMXl8",
    color: "#E53935",
  },
  // 虚拟 U 卡
  {
    id: "bitget-virtual-card",
    platform: "Bitget 虚拟 U 卡",
    category: "VirtualCard",
    description: "Bitget 平台虚拟 U 卡服务",
    benefit: "便捷的数字资产支付解决方案",
    highlightValue: "数字支付",
    badge: "新上线",
    featured: true,
    claimedCount: 670,
    code: "89zQdt",
    link: "https://web3.bitget.com/invite/card/89zQdt?channel=Copylink&utm_source=newInviteRebate&inviteCode=89zQdt",
    iconUrl: "https://www.bitget.com",
    tutorialLink: "/articles/vcard/WK8p1cCV",
    color: "#03C87C",
  },
  {
    id: "safepal-virtual-card",
    platform: "SafePal 虚拟 U 卡",
    category: "VirtualCard",
    description: "SafePal 钱包虚拟 U 卡服务",
    benefit: "安全便捷的加密货币支付卡",
    highlightValue: "安全支付",
    claimedCount: 430,
    code: "884823",
    link: "https://www.safepal.com/bank/register?referral=884823",
    iconUrl: "https://www.safepal.com",
    tutorialLink: "/articles/vcard/E4lD5AIn",
    color: "#4F46E5",
  },
  {
    id: "bybit-virtual-card",
    platform: "Bybit 虚拟 U 卡",
    category: "VirtualCard",
    description: "Bybit 平台虚拟 U 卡，支持 10% 消费返现",
    benefit: "开卡即享消费返现，支持 Google Pay / Apple Pay",
    highlightValue: "10% 返现",
    badge: "新上线",
    claimedCount: 310,
    code: "JJKZWA4",
    link: "https://www.bybit.com/en/card/",
    iconUrl: "https://www.bybit.com",
    tutorialLink: "/articles/vcard/wYKRLDvK",
    color: "#F8A33C",
  },
  // A 股券商
  {
    id: "china-galaxy",
    platform: "银河证券",
    category: "AStocks",
    description: "A股大型券商，ETF永久免五，多品种低佣",
    benefit: "入金1.5万放2个月，ETF永久免五",
    highlightValue: "永久免五",
    badge: "编辑推荐",
    claimedCount: 0,
    code: null,
    link: "https://www.chinastock.com.cn/",
    iconUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/9c/33/30/9c3330e7-b543-f9e6-65c3-bceeeac2d132/AppIcon-0-0-1x_U007emarketing-0-6-0-85-220.png/512x512bb.jpg",
    tutorialLink: null,
    color: "#C8102E",
    contactWeChat: true,
    details: [
      "##交易费率",
      "ETF/LOF：万0.5，1毛起（免五）",
      "股票：万0.86，50万↑万0.8，5元起",
      "可转债：万0.5，沪0.1元/深0.2元起",
      "北交所：万2，港股通：万0.8（不免五）",
      "国债逆回购：1折，500万以上0.1折",
      "LOF申购1折，赎回5折",
      "##融资利率",
      "50~100万：3.98%",
      "100~200万：3.78%",
      "200~400万：3.58%",
      "400~700万：3.38%",
      "700~1000万：3.18%",
      "1000万以上：3%以下",
      "##其他权益",
      "新客理财：6%，5万28天",
      "Level2+智能交易VIP：新客3个月",
    ],
  },
  {
    id: "huatai-securities",
    platform: "华泰证券",
    category: "AStocks",
    description: "A股头部券商，SMART量化交易，新客行情12个月",
    benefit: "VIP佣金万1，新客赠12个月10档行情",
    highlightValue: "万1",
    claimedCount: 0,
    code: null,
    link: "https://www.htsc.com.cn/",
    iconUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/f0/4d/ce/f04dceaa-9b0b-771e-5af7-2060f57bec2d/AppIcon-0-0-1x_U007emarketing-0-8-0-0-85-220.png/512x512bb.jpg",
    tutorialLink: null,
    color: "#E60012",
    contactWeChat: true,
    details: [
      "##交易费率",
      "股票：万1，单笔5元起",
      "ETF/LOF：万0.5，单笔5元起",
      "可转债：万0.4，深0.1元/沪1元起",
      "国债逆回购：1折，0.01元起",
      "北交所：万2.25，港股通：万1.3",
      "##融资利率",
      "融资ETF：3.09%~3.49%",
      "股票 0~100万：3.99%",
      "股票 100~500万：3.7%",
      "股票 500~1000万：3.5%",
      "股票 1000~5000万：3.2%",
      "##新客权益",
      "理财4%：1.1万×364天→440元 / 2万×182天→400元 / 5万×70天→384元 / 10万×35天→384元",
      "理财6.08%：0.5万×35天→29元（两档可叠加）",
      "新客行情：赠12个月10档，参与活动最高10年",
      "SMART量化：50万手机端，300万PC端",
      "主力密码+趋势顶底功能：新客3个月",
    ],
  },
  // 链上钱包
  {
    id: "binance-wallet",
    platform: "币安钱包",
    category: "Wallet",
    description: "币安 Web3 钱包，支持多链资产管理",
    benefit: "安全易用的多链钱包，支持 DeFi、NFT 与跨链",
    highlightValue: "多链",
    badge: "编辑推荐",
    featured: true,
    claimedCount: 560,
    code: "WISE555",
    link: "https://web3.binance.com/referral?ref=WISE555",
    iconUrl: "https://www.binance.com",
    tutorialLink: null,
    tutorialImage: "/images/perks/币安钱包返现.png",
    color: "#F3BA2F",
  },
  {
    id: "okx-wallet",
    platform: "欧易钱包",
    category: "Wallet",
    description: "OKX Web3 钱包，一站式链上资产管理",
    benefit: "多链钱包，支持 DeFi 交互、NFT 与跨链桥",
    highlightValue: "多链",
    claimedCount: 380,
    code: "WISE6666",
    link: "https://web3.okx.com/join/WISE6666",
    iconUrl: "https://www.okx.com",
    tutorialLink: null,
    tutorialImage: "/images/perks/欧易钱包返现.png",
    color: "#000000",
  },
];
