export interface Resource {
  name: string;
  desc: string;
  url: string; // 默认链接（向后兼容）
  invitationLink?: string; // 邀请链接（用户点击时跳转，如果没有则使用 url）
  iconUrl?: string; // 官方网站 URL，用于获取图标（可选，如果没有则使用 url）
  icon?: string; // Lucide icon name or image URL
  tag?: "Recommended" | "Official" | "Popular"; // Optional curated tag
  rating: number; // Rating from 1-5
}

export interface ResourceCategory {
  id: string;
  label: string;
  emoji: string;
  items: Resource[];
}

export const resourceCategories: ResourceCategory[] = [
  {
    id: "exchanges",
    label: "交易所",
    emoji: "🏦",
    items: [
      {
        name: "Binance",
        desc: "全球最大的加密货币交易所",
        url: "https://www.binance.com",
        invitationLink: "https://www.bsmkweb.cc/register?ref=WISEBNB1",
        iconUrl: "https://www.binance.com",
        icon: "Coins",
        tag: "Recommended",
        rating: 5,
      },
      {
        name: "OKX",
        desc: "全球领先的加密货币交易平台",
        url: "https://www.okx.com",
        invitationLink: "https://www.firgrouxywebb.com/join/WISE6666",
        iconUrl: "https://www.okx.com",
        icon: "TrendingUp",
        rating: 4.5,
      },
      {
        name: "Coinbase",
        desc: "美国最大的加密货币交易所",
        url: "https://www.coinbase.com",
        icon: "DollarSign",
        rating: 4.5,
      },
      {
        name: "Kraken",
        desc: "安全可靠的加密货币交易所",
        url: "https://www.kraken.com",
        icon: "Shield",
        rating: 4.5,
      },
      {
        name: "Bybit",
        desc: "专业的衍生品交易平台",
        url: "https://www.bybit.com",
        invitationLink: "https://partner.bybit.com/b/WISE5130",
        iconUrl: "https://www.bybit.com",
        icon: "TrendingUp",
        tag: "Popular",
        rating: 4.5,
      },
      {
        name: "Gate.io",
        desc: "全球领先的数字资产交易平台",
        url: "https://www.gate.io",
        icon: "Coins",
        rating: 4,
      },
      {
        name: "KuCoin",
        desc: "用户友好的加密货币交易所",
        url: "https://www.kucoin.com",
        icon: "Coins",
        rating: 4,
      },
      {
        name: "Bitget",
        desc: "创新的加密货币交易和跟单平台",
        url: "https://www.bitget.com",
        invitationLink: "https://partner.bitget.cafe/bg/8ax9wf4r",
        iconUrl: "https://www.bitget.com",
        icon: "TrendingUp",
        rating: 4,
      },
    ],
  },
  {
    id: "market-data",
    label: "行情数据",
    emoji: "📊",
    items: [
      {
        name: "TradingView",
        desc: "专业的图表分析平台",
        url: "https://www.tradingview.com",
        icon: "BarChart3",
        tag: "Popular",
        rating: 5,
      },
      {
        name: "CoinMarketCap",
        desc: "全球最大的加密货币市值追踪网站",
        url: "https://coinmarketcap.com",
        icon: "TrendingUp",
        tag: "Popular",
        rating: 4.5,
      },
      {
        name: "DeFiLlama",
        desc: "DeFi 协议总锁仓量追踪",
        url: "https://defillama.com",
        icon: "PiggyBank",
        rating: 5,
      },
      {
        name: "Coinglass",
        desc: "加密货币期货数据和分析",
        url: "https://www.coinglass.com",
        icon: "Activity",
        rating: 4.5,
      },
      {
        name: "Glassnode",
        desc: "链上数据分析平台",
        url: "https://glassnode.com",
        icon: "Network",
        rating: 4.5,
      },
      {
        name: "CryptoQuant",
        desc: "加密货币链上数据和分析",
        url: "https://cryptoquant.com",
        icon: "Database",
        rating: 4.5,
      },
      {
        name: "CoinGecko",
        desc: "全面的加密货币市场数据",
        url: "https://www.coingecko.com",
        icon: "Coins",
        tag: "Popular",
        rating: 5,
      },
      {
        name: "IntoTheBlock",
        desc: "链上和市场数据分析",
        url: "https://intotheblock.com",
        icon: "BarChart3",
        rating: 4.5,
      },
      {
        name: "Santiment",
        desc: "加密货币市场情绪分析",
        url: "https://santiment.net",
        icon: "Activity",
        rating: 4.5,
      },
      {
        name: "Fear & Greed Index",
        desc: "加密货币市场情绪指数",
        url: "https://alternative.me/crypto/fear-and-greed-index/",
        icon: "TrendingUp",
        rating: 4.5,
      },
      {
        name: "CoinStats",
        desc: "加密货币投资组合追踪",
        url: "https://coinstats.app",
        icon: "Wallet",
        rating: 4,
      },
      {
        name: "Blockchain.com",
        desc: "区块链数据和分析平台",
        url: "https://www.blockchain.com",
        icon: "Database",
        rating: 4,
      },
    ],
  },
  {
    id: "security-infra",
    label: "安全/基建",
    emoji: "🛡️",
    items: [
      {
        name: "L2Beat",
        desc: "以太坊Layer2最权威数据",
        url: "https://l2beat.com",
        icon: "BarChart3",
        rating: 5,
      },
      {
        name: "Rabby Wallet",
        desc: "专为DeFi用户设计的安全钱包",
        url: "https://rabby.io",
        icon: "Wallet",
        rating: 5,
      },
      {
        name: "GoPlus Security",
        desc: "快速检测代币合约安全性",
        url: "https://gopluslabs.io",
        icon: "Shield",
        rating: 4.5,
      },
      {
        name: "MetaMask",
        desc: "最流行的以太坊钱包",
        url: "https://metamask.io",
        icon: "Wallet",
        tag: "Popular",
        rating: 5,
      },
      {
        name: "Ledger",
        desc: "硬件钱包安全解决方案",
        url: "https://www.ledger.com",
        icon: "Shield",
        tag: "Recommended",
        rating: 5,
      },
      {
        name: "CertiK",
        desc: "区块链安全审计和监控",
        url: "https://www.certik.com",
        icon: "Shield",
        rating: 4.5,
      },
    ],
  },
  {
    id: "macro-tools",
    label: "宏观/工具",
    emoji: "🌍",
    items: [
      {
        name: "FedWatch Tool",
        desc: "美联储加息降息概率预测",
        url: "https://www.cmegroup.com/trading/interest-rates/cme-fedwatch-tool.html",
        icon: "TrendingUp",
        rating: 5,
      },
      {
        name: "CoinGecko",
        desc: "比CMC更准确的代币数据聚合",
        url: "https://coingecko.com",
        icon: "Coins",
        rating: 5,
      },
      {
        name: "Cryptorank",
        desc: "详细的代币解锁与IDO数据",
        url: "https://cryptorank.io",
        icon: "BarChart3",
        rating: 4.5,
      },
      {
        name: "美联储官网",
        desc: "美国联邦储备系统官方网站",
        url: "https://www.federalreserve.gov",
        icon: "Building2",
        tag: "Official",
        rating: 4.5,
      },
      {
        name: "Investing.com",
        desc: "全球金融市场数据和新闻",
        url: "https://www.investing.com",
        icon: "Globe",
        rating: 4,
      },
      {
        name: "FRED",
        desc: "美联储经济数据数据库",
        url: "https://fred.stlouisfed.org",
        icon: "Database",
        rating: 4,
      },
      {
        name: "Trading Economics",
        desc: "全球宏观经济数据和预测",
        url: "https://tradingeconomics.com",
        icon: "Globe",
        rating: 4.5,
      },
      {
        name: "World Bank Data",
        desc: "世界银行开放数据",
        url: "https://data.worldbank.org",
        icon: "Database",
        tag: "Official",
        rating: 4.5,
      },
      {
        name: "IMF Data",
        desc: "国际货币基金组织数据",
        url: "https://www.imf.org/en/Data",
        icon: "Database",
        tag: "Official",
        rating: 4.5,
      },
      {
        name: "Yahoo Finance",
        desc: "全球金融市场数据和新闻",
        url: "https://finance.yahoo.com",
        icon: "DollarSign",
        tag: "Popular",
        rating: 4.5,
      },
      {
        name: "MarketWatch",
        desc: "实时市场数据和财经新闻",
        url: "https://www.marketwatch.com",
        icon: "BarChart3",
        rating: 4,
      },
      {
        name: "CNBC",
        desc: "全球财经新闻和市场分析",
        url: "https://www.cnbc.com",
        icon: "Newspaper",
        rating: 4,
      },
    ],
  },
  {
    id: "stock-brokers",
    label: "美股券商",
    emoji: "📈",
    items: [
      {
        name: "Interactive Brokers",
        desc: "全球领先的在线券商",
        url: "https://www.interactivebrokers.com",
        invitationLink: "https://ibkr.com/referral/fengyang247",
        iconUrl: "https://www.interactivebrokers.com",
        icon: "Briefcase",
        tag: "Recommended",
        rating: 5,
      },
      {
        name: "Charles Schwab",
        desc: "美国大型券商和银行",
        url: "https://www.schwab.com",
        icon: "Building2",
        rating: 4.5,
      },
      {
        name: "Fidelity",
        desc: "美国最大的投资管理公司之一",
        url: "https://www.fidelity.com",
        icon: "PiggyBank",
        rating: 4.5,
      },
      {
        name: "TD Ameritrade",
        desc: "知名在线券商（已并入 Schwab）",
        url: "https://www.tdameritrade.com",
        icon: "TrendingUp",
        rating: 4,
      },
      {
        name: "E*TRADE",
        desc: "在线股票和期权交易平台",
        url: "https://us.etrade.com",
        icon: "TrendingUp",
        rating: 4.5,
      },
      {
        name: "Robinhood",
        desc: "零佣金股票和加密货币交易",
        url: "https://robinhood.com",
        icon: "Coins",
        tag: "Popular",
        rating: 4,
      },
      {
        name: "Webull",
        desc: "免费股票交易和投资平台",
        url: "https://www.webull.com",
        icon: "BarChart3",
        rating: 4,
      },
      {
        name: "Merrill Edge",
        desc: "美林银行在线投资平台",
        url: "https://www.merrilledge.com",
        icon: "Briefcase",
        rating: 4,
      },
    ],
  },
  {
    id: "on-chain-tools",
    label: "链上工具",
    emoji: "🔗",
    items: [
      {
        name: "Dune Analytics",
        desc: "最强大的链上数据可视化平台",
        url: "https://dune.com",
        icon: "BarChart3",
        rating: 5,
      },
      {
        name: "DeBank",
        desc: "最好用的多链资产仪表盘",
        url: "https://debank.com",
        icon: "Wallet",
        rating: 5,
      },
      {
        name: "DexScreener",
        desc: "实时监控土狗和DEX交易行情",
        url: "https://dexscreener.com",
        icon: "Activity",
        rating: 5,
      },
      {
        name: "Revoke.cash",
        desc: "取消代币授权，保护资产安全",
        url: "https://revoke.cash",
        icon: "Shield",
        rating: 5,
      },
      {
        name: "Arkham",
        desc: "加密货币情报与地址追踪",
        url: "https://www.arkhamintelligence.com",
        icon: "Eye",
        rating: 4.5,
      },
      {
        name: "Etherscan",
        desc: "以太坊区块链浏览器",
        url: "https://etherscan.io",
        icon: "Search",
        tag: "Official",
        rating: 4.5,
      },
      {
        name: "BscScan",
        desc: "BSC 区块链浏览器",
        url: "https://bscscan.com",
        icon: "Search",
        rating: 4,
      },
      {
        name: "Nansen",
        desc: "链上智能资金追踪",
        url: "https://www.nansen.ai",
        icon: "Eye",
        rating: 4.5,
      },
      {
        name: "Zerion",
        desc: "DeFi 投资组合管理",
        url: "https://zerion.io",
        icon: "Wallet",
        rating: 4,
      },
      {
        name: "Polygonscan",
        desc: "Polygon 区块链浏览器",
        url: "https://polygonscan.com",
        icon: "Search",
        rating: 4,
      },
      {
        name: "Arbiscan",
        desc: "Arbitrum 区块链浏览器",
        url: "https://arbiscan.io",
        icon: "Search",
        rating: 4,
      },
      {
        name: "Optimistic Etherscan",
        desc: "Optimism 区块链浏览器",
        url: "https://optimistic.etherscan.io",
        icon: "Search",
        rating: 4,
      },
      {
        name: "Zapper",
        desc: "DeFi 投资组合追踪和管理",
        url: "https://zapper.fi",
        icon: "Wallet",
        rating: 4.5,
      },
      {
        name: "ApeBoard",
        desc: "多链 DeFi 仪表盘",
        url: "https://apeboard.finance",
        icon: "BarChart3",
        rating: 4,
      },
      {
        name: "DefiLlama Yield",
        desc: "DeFi 收益率追踪和比较",
        url: "https://defillama.com/yields",
        icon: "PiggyBank",
        rating: 4.5,
      },
      {
        name: "Token Unlocks",
        desc: "代币解锁时间表追踪",
        url: "https://token.unlocks.app",
        icon: "Activity",
        rating: 4.5,
      },
      {
        name: "L2BEAT",
        desc: "Layer2 项目风险评估",
        url: "https://l2beat.com",
        icon: "Shield",
        rating: 5,
      },
      {
        name: "DefiPulse",
        desc: "DeFi 协议总锁仓量追踪",
        url: "https://defipulse.com",
        icon: "BarChart3",
        rating: 4,
      },
    ],
  },
  {
    id: "research-news",
    label: "研报/资讯",
    emoji: "📰",
    items: [
      {
        name: "Messari",
        desc: "机构级加密货币研究报告",
        url: "https://messari.io",
        icon: "FileText",
        rating: 5,
      },
      {
        name: "Token Terminal",
        desc: "基于基本面的加密项目财务数据",
        url: "https://tokenterminal.com",
        icon: "BarChart3",
        rating: 5,
      },
      {
        name: "Foresight News",
        desc: "高质量的Web3深度内容聚合",
        url: "https://foresightnews.pro",
        icon: "Newspaper",
        rating: 4.5,
      },
      {
        name: "Wu Blockchain",
        desc: "独家且深入的行业调查报道",
        url: "https://wublock.substack.com",
        icon: "FileText",
        rating: 4.5,
      },
      {
        name: "BlockBeats",
        desc: "及时的行业新闻与快讯",
        url: "https://theblockbeats.info",
        icon: "Newspaper",
        rating: 4,
      },
      {
        name: "Bloomberg",
        desc: "全球财经新闻和数据",
        url: "https://www.bloomberg.com",
        icon: "Newspaper",
        tag: "Popular",
        rating: 4.5,
      },
      {
        name: "CoinDesk",
        desc: "加密货币新闻和分析",
        url: "https://www.coindesk.com",
        icon: "Coins",
        rating: 4,
      },
      {
        name: "The Block",
        desc: "加密货币和区块链新闻",
        url: "https://www.theblock.co",
        icon: "FileText",
        rating: 4,
      },
      {
        name: "Decrypt",
        desc: "加密货币和Web3新闻",
        url: "https://decrypt.co",
        icon: "Newspaper",
        rating: 4,
      },
      {
        name: "CoinTelegraph",
        desc: "加密货币新闻和分析",
        url: "https://cointelegraph.com",
        icon: "Newspaper",
        tag: "Popular",
        rating: 4.5,
      },
      {
        name: "The Defiant",
        desc: "DeFi 新闻和分析",
        url: "https://thedefiant.io",
        icon: "FileText",
        rating: 4.5,
      },
      {
        name: "Bankless",
        desc: "加密货币和DeFi教育内容",
        url: "https://banklesshq.com",
        icon: "BookOpen",
        rating: 4.5,
      },
      {
        name: "Delphi Digital",
        desc: "加密货币研究和分析",
        url: "https://members.delphidigital.io",
        icon: "FileText",
        rating: 5,
      },
      {
        name: "Chainalysis",
        desc: "区块链数据和分析报告",
        url: "https://www.chainalysis.com",
        icon: "BarChart3",
        rating: 4.5,
      },
      {
        name: "CryptoSlate",
        desc: "加密货币新闻和数据",
        url: "https://cryptoslate.com",
        icon: "Coins",
        rating: 4,
      },
      {
        name: "BeInCrypto",
        desc: "加密货币新闻和教育",
        url: "https://beincrypto.com",
        icon: "Newspaper",
        rating: 4,
      },
    ],
  },
  {
    id: "education",
    label: "投资教育",
    emoji: "📚",
    items: [
      {
        name: "Investopedia",
        desc: "投资教育平台",
        url: "https://www.investopedia.com",
        icon: "BookOpen",
        tag: "Recommended",
        rating: 5,
      },
      {
        name: "Seeking Alpha",
        desc: "投资分析和研究平台",
        url: "https://seekingalpha.com",
        icon: "TrendingUp",
        rating: 4.5,
      },
      {
        name: "Morningstar",
        desc: "基金和股票研究平台",
        url: "https://www.morningstar.com",
        icon: "Star",
        rating: 4.5,
      },
      {
        name: "Yahoo Finance",
        desc: "财经新闻和数据平台",
        url: "https://finance.yahoo.com",
        icon: "DollarSign",
        rating: 4,
      },
      {
        name: "Khan Academy",
        desc: "免费投资和金融课程",
        url: "https://www.khanacademy.org",
        icon: "BookOpen",
        tag: "Recommended",
        rating: 5,
      },
      {
        name: "Coursera Finance",
        desc: "在线金融和投资课程",
        url: "https://www.coursera.org",
        icon: "BookOpen",
        rating: 4.5,
      },
      {
        name: "Crypto.com University",
        desc: "加密货币和区块链教育",
        url: "https://crypto.com/university",
        icon: "Coins",
        rating: 4.5,
      },
      {
        name: "Binance Academy",
        desc: "区块链和加密货币教育",
        url: "https://academy.binance.com",
        icon: "BookOpen",
        rating: 4.5,
      },
    ],
  },
];
