export interface RoadmapStep {
  id: string;
  title: string;
  description: string;
  articleLink: string | null; // Link to article or null if no article yet
  estimatedTime?: string; // e.g., "15分钟"
  prerequisites?: string[]; // IDs of steps that must be completed first
}

export type RoadmapCategory = "investment" | "us_stocks" | "web3" | "index_investing" | "overseas_earning";

export interface Roadmap {
  id: string;
  title: string;
  description: string;
  category: RoadmapCategory;
  icon: string; // Emoji or icon name
  color: string; // Tailwind color class
  steps: RoadmapStep[];
  estimatedTotalTime?: string;
}

export const roadmaps: Roadmap[] = [
  // 已注释：美股投资指南 - 链接: /roadmap/overseas-investment
  // {
  //   id: "overseas-investment",
  //   title: "美股投资指南",
  //   description: "从开户到交易，全面了解美股市场的基础知识和操作流程",
  //   category: "us_stocks",
  //   icon: "🌍",
  //   color: "blue",
  //   estimatedTotalTime: "2.5小时",
  //   steps: [
  //     {
  //       id: "step-1",
  //       title: "了解美股市场",
  //       description: "学习美股市场的基本规则、交易时间、市场结构等基础知识",
  //       articleLink: "/tweets#us-stocks-basics",
  //       estimatedTime: "25分钟",
  //     },
  //     {
  //       id: "step-2",
  //       title: "选择美股券商",
  //       description: "比较不同美股券商的优缺点，选择最适合自己的平台",
  //       articleLink: "/perks",
  //       estimatedTime: "20分钟",
  //       prerequisites: ["step-1"],
  //     },
  //     {
  //       id: "step-3",
  //       title: "完成账户开立",
  //       description: "了解开户流程、所需材料，完成账户验证和入金",
  //       articleLink: "/tweets#account-opening",
  //       estimatedTime: "30分钟",
  //       prerequisites: ["step-2"],
  //     },
  //     {
  //       id: "step-4",
  //       title: "学习基础分析",
  //       description: "掌握基本面分析、技术分析的基础知识，学会阅读财报",
  //       articleLink: "/tweets#stock-analysis",
  //       estimatedTime: "45分钟",
  //       prerequisites: ["step-3"],
  //     },
  //     {
  //       id: "step-5",
  //       title: "执行第一笔交易",
  //       description: "学习如何下单、设置订单类型，完成你的第一笔美股交易",
  //       articleLink: null,
  //       estimatedTime: "30分钟",
  //       prerequisites: ["step-4"],
  //     },
  //   ],
  // },
  // 已注释：Web3 零基础入门 - 链接: /roadmap/web3-onboarding
  // {
  //   id: "web3-onboarding",
  //   title: "Web3 零基础入门",
  //   description: "从钱包创建到 DeFi 操作，完整掌握 Web3 基础知识",
  //   category: "web3",
  //   icon: "🔷",
  //   color: "purple",
  //   estimatedTotalTime: "3小时",
  //   steps: [
  //     {
  //       id: "step-1",
  //       title: "创建加密钱包",
  //       description: "学习如何创建 MetaMask 或 Rabby 钱包，安全保存助记词",
  //       articleLink: "/resources",
  //       estimatedTime: "20分钟",
  //     },
  //     {
  //       id: "step-2",
  //       title: "了解 Gas 费用",
  //       description: "理解以太坊网络的手续费机制，学会估算和优化 Gas 费用",
  //       articleLink: "/tweets#gas-fees",
  //       estimatedTime: "15分钟",
  //       prerequisites: ["step-1"],
  //     },
  //     {
  //       id: "step-3",
  //       title: "首次跨链转账",
  //       description: "学习如何将资产从交易所转移到钱包，完成首次链上操作",
  //       articleLink: "/tweets#first-transfer",
  //       estimatedTime: "25分钟",
  //       prerequisites: ["step-2"],
  //     },
  //     {
  //       id: "step-4",
  //       title: "探索 DeFi 协议",
  //       description: "了解流动性挖矿、借贷、DEX 等核心 DeFi 概念和操作",
  //       articleLink: "/tweets#defi-basics",
  //       estimatedTime: "40分钟",
  //       prerequisites: ["step-3"],
  //     },
  //     {
  //       id: "step-5",
  //       title: "安全最佳实践",
  //       description: "学习如何识别钓鱼网站、保护私钥、避免常见安全陷阱",
  //       articleLink: "/tweets#web3-security",
  //       estimatedTime: "30分钟",
  //       prerequisites: ["step-4"],
  //     },
  //   ],
  // },
  {
    id: "crypto-trading",
    title: "加密货币CEX 交易所入门",
    description: "详细介绍四大CEX 交易所注册&入金&交易教程",
    category: "web3",
    icon: "📈",
    color: "yellow",
    estimatedTotalTime: "4小时",
    steps: [
      {
        id: "step-1",
        title: "币安",
        description: "20% 永久交易&钱包手续费减免",
        articleLink: "https://x.com/WiseInvest513/status/1970757919500120451",
        estimatedTime: "30分钟",
      },
      {
        id: "step-2",
        title: "欧易",
        description: "20% 永久交易&钱包手续费减免",
        articleLink: "https://x.com/WiseInvest513/status/1953466482576556465",
        estimatedTime: "45分钟",
        prerequisites: ["step-1"],
      },
      {
        id: "step-3",
        title: "Bitget",
        description: "20% 手续费减免&新用户注册专享福利",
        articleLink: "https://x.com/WiseInvest513/status/1980140049267343697",
        estimatedTime: "30分钟",
        prerequisites: ["step-2"],
      },
      {
        id: "step-4",
        title: "Bybit",
        description: "20% 手续费减免&注册即享交易优惠",
        articleLink: "https://x.com/WiseInvest513/status/1980641416243212480",
        estimatedTime: "50分钟",
        prerequisites: ["step-3"],
      },
    ],
  },
  {
    id: "binance-alpha-okx-boost",
    title: "币安 alpha/欧易 Boost 空投",
    description: "完整掌握币安 Alpha 和欧易 Boost 空投获取流程，最大化空投收益",
    category: "web3",
    icon: "🎁",
    color: "purple",
    estimatedTotalTime: "3小时",
    steps: [
      {
        id: "step-1",
        title: "人生作弊指南启动贴",
        description: "正式启动币安 alpha /欧易 Boost 空投",
        articleLink: "https://x.com/WiseInvest513/status/1984643889765212323",
        estimatedTime: "25分钟",
      },
      {
        id: "step-2",
        title: "币安 alpha&欧易 Boost 视频教程",
        description: "详细讲解如何刷积分",
        articleLink: "https://youtu.be/frRapUcAFPI?si=XzdjTMj8waib6nP5",
        estimatedTime: "30分钟",
        prerequisites: ["step-1"],
      },
      {
        id: "step-3",
        title: "欧易 Boos 刷高倍率代币文字教程",
        description: "文字版本讲解我们如何刷高积分，记得绑定邀请码：WISE6666 获取到 20% 手续费减免",
        articleLink: "https://x.com/WiseInvest513/status/2003449023223726252",
        estimatedTime: "40分钟",
        prerequisites: ["step-2"],
      },
      {
        id: "step-4",
        title: "总结收入",
        description: "总结刷 alpha 和欧易 Boost 的部分收入，持续坚持",
        articleLink: "https://x.com/WiseInvest513/status/2006312197517934774",
        estimatedTime: "40分钟",
        prerequisites: ["step-3"],
      },
    ],
  },
  {
    id: "virtual-card-fund-repatriation",
    title: "如何利用虚拟 U 卡进行资金回国",
    description: "掌握使用虚拟 U 卡将海外资金安全便捷地转回国内的方法和流程",
    category: "web3",
    icon: "💳",
    color: "purple",
    estimatedTotalTime: "2.5小时",
    steps: [
      {
        id: "step-1",
        title: "开设 Bitget 虚拟 U 卡",
        description: "Bitget 虚拟 U 卡可以用作在国内进行资金的小额消费，费率友好，无损耗",
        articleLink: "https://youtu.be/ZxElS0gVpY4?si=PjRgbtJJe2_xmRFM",
        estimatedTime: "20分钟",
      },
      {
        id: "step-2",
        title: "开设 SafePal 虚拟 U 卡",
        description: "SafePal 虚拟 U 卡可以用作国内/证券汇款，资金回转方便",
        articleLink: "https://youtu.be/1Lw8VssYFNE?si=RdhTTA9IVjsMuipA",
        estimatedTime: "30分钟",
        prerequisites: ["step-1"],
      },
      {
        id: "step-3",
        title: "SafePal 虚拟 U 卡汇款会国内银行",
        description: "SafePal 虚拟 U 卡可接收加密货币，转为法币直接回国",
        articleLink: "https://youtu.be/WWZiufXWkqE?si=j7hRO4e3ZIrWPJ9c",
        estimatedTime: "25分钟",
        prerequisites: ["step-2"],
      },
    ],
  },
  {
    id: "us-stocks-basics",
    title: "美股新手上路",
    description: "从零开始学习多种在国内投资美股的方式",
    category: "investment",
    icon: "📊",
    color: "green",
    estimatedTotalTime: "2小时",
    steps: [
      {
        id: "step-1",
        title: "2026 年全网最全最详细普通人购买美股教程",
        description: "美股教程导航篇",
        articleLink: "https://x.com/WiseInvest513/status/2008529401483546953",
        estimatedTime: "30分钟",
      },
      {
        id: "step-2",
        title: "2026 年全网最全最详细众安银行投资美股教程！",
        description: "详细介绍如何使用众安银行投资美股",
        articleLink: "https://x.com/WiseInvest513/status/2008539052673552651",
        estimatedTime: "20分钟",
        prerequisites: ["step-1"],
      },
      {
        id: "step-3",
        title: "2026 年全网最全最详细券商 APP投资美股教程！",
        description: "详细介绍如何使用盈立证券投资美股",
        articleLink: "https://x.com/WiseInvest513/status/2008543869684883923",
        estimatedTime: "25分钟",
        prerequisites: ["step-2"],
      },
      {
        id: "step-4",
        title: "2026 年全网最全最详细券商 APP投资美股教程!",
        description: "详细介绍如何使用币安、Bitget、麦通投资美股",
        articleLink: "https://x.com/WiseInvest513/status/2008543869684883923",
        estimatedTime: "15分钟",
        prerequisites: ["step-3"],
      },
    ],
  },
  {
    id: "low-cost-us-stocks-guide",
    title: "最低成本从零到一投资美股指南",
    description: "以最低成本完成美股投资全流程，从开户到交易，最大化节省费用",
    category: "us_stocks",
    icon: "💵",
    color: "green",
    estimatedTotalTime: "2.5小时",
    steps: [
      {
        id: "step-1",
        title: "开兴业寰宇人生借记卡&英国Ifast数字银行",
        description: "兴业寰宇人生转账免手续费，Ifast 英国数字银行不需要其他证件即可开户",
        articleLink: "https://youtu.be/2LcPWwwMSqw?si=-cRUXSPESTTRlBYOs",
        estimatedTime: "20分钟",
      },
      {
        id: "step-2",
        title: "开 Wise",
        description: "如果英国 Ifast 数字银行不能入金，可以安排 Wise，无门槛",
        articleLink: "https://youtu.be/BB7KtDfbXsU?si=isTGN8mzgMIn8L27",
        estimatedTime: "30分钟",
        prerequisites: ["step-1"],
      },
      {
        id: "step-3",
        title: "开盈立证券",
        description: "国内唯一仅凭借身份证即可开户的券商公司",
        articleLink: "https://x.com/WiseInvest513/status/1970789148605948258",
        estimatedTime: "25分钟",
        prerequisites: ["step-2"],
      },
      {
        id: "step-4",
        title: "Ifast 入金盈立证券",
        description: "资金从国内卡到兴业，兴业到 Ifast/Wise，然后再到盈立，成功投资美股",
        articleLink: "https://youtu.be/o94W7r8M2kY?si=ts_pE_aKBJ18dlYs",
        estimatedTime: "35分钟",
        prerequisites: ["step-3"],
      },
    ],
  },
  {
    id: "index-investing-basics",
    title: "指数投资入门",
    description: "学习指数基金投资策略，掌握长期稳健的投资方法",
    category: "index_investing",
    icon: "📊",
    color: "blue",
    estimatedTotalTime: "2小时",
    steps: [
      {
        id: "step-1",
        title: "2025 年之股票、国债、基金一文讲清全网最全教程",
        description: "了解什么是股票、国债、以及基金都是什么含义",
        articleLink: "/https://x.com/WiseInvest513/status/1958511704951959881",
        estimatedTime: "25分钟",
      },
      {
        id: "step-2",
        title: "投资纳斯达 100 和标普 500如何进行配比",
        description: "学习在不同的阶段我们应该如何配比纳指和标普",
        articleLink: "https://x.com/WiseInvest513/status/1958871136273662159",
        estimatedTime: "30分钟",
        prerequisites: ["step-1"],
      },
      {
        id: "step-3",
        title: "聊到的投资路上的弯路",
        description: "聊我们在价值投资路上应该避免走哪些弯路",
        articleLink: "https://x.com/WiseInvest513/status/1958832406200557931",
        estimatedTime: "25分钟",
        prerequisites: ["step-2"],
      },
      {
        id: "step-4",
        title: "场内和场外指数基金的不同",
        description: "聊场内和场外的基金都有什么区别",
        articleLink: "https://x.com/WiseInvest513/status/1959917167291367831",
        estimatedTime: "30分钟",
        prerequisites: ["step-3"],
      },
      {
        id: "step-5",
        title: "2025 年之如何在美股不动脑子成为百万富豪实操版",
        description: "分享我们如何利用长线投资理论在美股不动脑子成为百万富翁",
        articleLink: "https://x.com/WiseInvest513/status/1957395396105519141",
        estimatedTime: "30分钟",
        prerequisites: ["step-4"],
      },
      {
        id: "step-6",
        title: "2025 年纳指/标普投资最全教程（初版）",
        description: "合集投资纳指/标普最全视频-初版",
        articleLink: "https://x.com/WiseInvest513/status/1959160397656924340",
        estimatedTime: "30分钟",
        prerequisites: ["step-5"],
      },
      {
        id: "step-7",
        title: "2025 年纳指/标普投资最全教程（终版）",
        description: "合集投资纳指/标普最全视频-终版",
        articleLink: "https://x.com/WiseInvest513/status/1960561387333411229",
        estimatedTime: "30分钟",
        prerequisites: ["step-6"],
      },
    ],
  },
  {
    id: "musk-creator-rewards",
    title: "如何获取马斯克工资",
    description: "完整掌握 Twitter/X 创作者激励计划，获取马斯克发放的创作者收益",
    category: "overseas_earning",
    icon: "💰",
    color: "yellow",
    estimatedTotalTime: "1.5小时",
    steps: [
      {
        id: "step-1",
        title: "开通众安银行用来接收工资",
        description: "成本最低的一定是开通 Wise 用来接受马斯克的工资",
        articleLink: "https://youtu.be/wqMChW__dyk?si=vTWFsoQfLQj-9Znh",
        estimatedTime: "25分钟",
      },
      {
        id: "step-2",
        title: "开通Wise 用来接接收工资",
        description: "如果可以的话，最好还是众安银行接收工资最好",
        articleLink: "https://youtu.be/h50rjDBiTIg?si=fT7EaGD8B2k2XRA_",
        estimatedTime: "40分钟",
        prerequisites: ["step-1"],
      },
      {
        id: "step-3",
        title: "有了卡之后就可以按照这个流程接收工资了",
        description: "详细介绍如何操作以及需要注意事项，注意需要护照号码",
        articleLink: "https://youtu.be/h50rjDBiTIg?si=tdBYNM9UPcQocY_P",
        estimatedTime: "25分钟",
        prerequisites: ["step-2"],
      },
    ],
  },
];

